// <auto-generated />
using System;
using GearNXT_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GearNXT_Backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518193843_AddAdminStaffProfiles")]
    partial class AddAdminStaffProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GearNXT_Backend.Models.AdminProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Office")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Office = "Head Office",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("PreferredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 100,
                            Notes = "Regular maintenance",
                            PreferredDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceType = "Full Vehicle Service",
                            Status = "Upcoming"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 100,
                            Notes = "Brake pads replaced",
                            PreferredDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceType = "Brake Inspection",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.CreditPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CreditPayments");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Address = "Kathmandu",
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anil.sharma@example.com",
                            Name = "Anil Sharma",
                            Phone = "9801112233"
                        },
                        new
                        {
                            Id = 101,
                            Address = "Lalitpur",
                            CreatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sita.karki@example.com",
                            Name = "Sita Karki",
                            Phone = "9802223344"
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PartId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("VendorId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Front brake pad set",
                            IsActive = true,
                            Name = "Brake Pad Set",
                            Price = 6800m,
                            StockQuantity = 25,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium oil filter",
                            IsActive = true,
                            Name = "Oil Filter",
                            Price = 2200m,
                            StockQuantity = 40,
                            VendorId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Engine air filter",
                            IsActive = true,
                            Name = "Air Filter",
                            Price = 1800m,
                            StockQuantity = 35,
                            VendorId = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heavy-duty clutch plate",
                            IsActive = true,
                            Name = "Clutch Plate",
                            Price = 9200m,
                            StockQuantity = 18,
                            VendorId = 3
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.PartRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PartRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 100,
                            Description = "OEM preferred",
                            PartName = "Turbocharger Kit",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.PurchaseInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PartId");

                    b.ToTable("PurchaseInvoiceItems");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent service.",
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 100,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DiscountApplied")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("SalesInvoices");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            CustomerId = 100,
                            DiscountAmount = 1250m,
                            DiscountApplied = true,
                            EmailSent = false,
                            GrandTotal = 11250m,
                            InvoiceDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceNumber = "INV-20260420-0001",
                            PaymentStatus = "Paid",
                            StaffId = 1,
                            TotalAmount = 12500m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 100,
                            DiscountAmount = 1650m,
                            DiscountApplied = true,
                            EmailSent = false,
                            GrandTotal = 14850m,
                            InvoiceDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceNumber = "INV-2026-1002",
                            PaymentStatus = "Credit",
                            StaffId = 1,
                            TotalAmount = 16500m
                        },
                        new
                        {
                            Id = 2001,
                            CustomerId = 101,
                            DiscountAmount = 1650m,
                            DiscountApplied = true,
                            EmailSent = false,
                            GrandTotal = 14850m,
                            InvoiceDate = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            InvoiceNumber = "INV-20260421-0002",
                            PaymentStatus = "Credit",
                            StaffId = 1,
                            TotalAmount = 16500m
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.SalesInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<string>("PartName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PartId");

                    b.ToTable("SalesInvoiceItems");

                    b.HasData(
                        new
                        {
                            Id = 3000,
                            InvoiceId = 2000,
                            PartId = 1,
                            PartName = "Brake Pad Set",
                            Quantity = 1,
                            UnitPrice = 6800m
                        },
                        new
                        {
                            Id = 3001,
                            InvoiceId = 2000,
                            PartId = 4,
                            PartName = "Clutch Plate",
                            Quantity = 1,
                            UnitPrice = 9200m
                        },
                        new
                        {
                            Id = 3002,
                            InvoiceId = 2001,
                            PartId = 2,
                            PartName = "Oil Filter",
                            Quantity = 3,
                            UnitPrice = 2200m
                        },
                        new
                        {
                            Id = 3003,
                            InvoiceId = 2001,
                            PartId = 3,
                            PartName = "Air Filter",
                            Quantity = 2,
                            UnitPrice = 1800m
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.StaffProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffProfiles");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gearnxt.com",
                            IsActive = true,
                            Name = "Admin",
                            PasswordHash = "$2a$11$Sw.RuMV4y9DiJY1wcIM6k.9/yQpmaqNBe3H7uB5Vr/htVWaYKp94i",
                            Phone = "9800000000",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("VehicleNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 100,
                            LicensePlate = "BA-2-PA-1234",
                            Make = "Honda",
                            Model = "City",
                            VehicleNumber = "VIN-ANIL-001",
                            Year = 2022
                        },
                        new
                        {
                            Id = 1001,
                            CreatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 101,
                            LicensePlate = "BA-3-PA-5678",
                            Make = "Toyota",
                            Model = "Corolla",
                            VehicleNumber = "VIN-SITA-001",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kathmandu",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "atlas@vendors.com",
                            IsActive = true,
                            Name = "Atlas Auto Supplies",
                            Phone = "9800000011"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pokhara",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "everest@vendors.com",
                            IsActive = true,
                            Name = "Everest Parts Co.",
                            Phone = "9800000022"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Biratnagar",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "terai@vendors.com",
                            IsActive = true,
                            Name = "Terai Traders",
                            Phone = "9800000033"
                        });
                });

            modelBuilder.Entity("GearNXT_Backend.Models.AdminProfile", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("GearNXT_Backend.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Appointment", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Customer", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("GearNXT_Backend.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Part", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.Vendor", "Vendor")
                        .WithMany("Parts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.PartRequest", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.Customer", "Customer")
                        .WithMany("PartRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.Vendor", "Vendor")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.PurchaseInvoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearNXT_Backend.Models.Part", "Part")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Review", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.SalesInvoice", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.Customer", "Customer")
                        .WithMany("SalesInvoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GearNXT_Backend.Models.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.SalesInvoiceItem", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.SalesInvoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GearNXT_Backend.Models.Part", "Part")
                        .WithMany("SalesInvoiceItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.StaffProfile", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("GearNXT_Backend.Models.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Vehicle", b =>
                {
                    b.HasOne("GearNXT_Backend.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PartRequests");

                    b.Navigation("Reviews");

                    b.Navigation("SalesInvoices");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Part", b =>
                {
                    b.Navigation("PurchaseInvoiceItems");

                    b.Navigation("SalesInvoiceItems");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.SalesInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("Customer");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("GearNXT_Backend.Models.Vendor", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("PurchaseInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
