using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace GearNXT_Backend.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddCustomerSalesManagement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "SalesInvoices",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "SalesInvoices",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Id",
                keyValue: 10);

            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Id",
                keyValue: 11);

            migrationBuilder.RenameColumn(
                name: "Subtotal",
                table: "SalesInvoices",
                newName: "TotalAmount");

            migrationBuilder.RenameColumn(
                name: "Discount",
                table: "SalesInvoices",
                newName: "DiscountAmount");

            migrationBuilder.RenameColumn(
                name: "Date",
                table: "SalesInvoices",
                newName: "InvoiceDate");

            migrationBuilder.AddColumn<int>(
                name: "StaffId",
                table: "SalesInvoices",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "Customers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Email = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: true),
                    Phone = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    Address = table.Column<string>(type: "character varying(250)", maxLength: 250, nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Customers", x => x.Id);
                });

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Parts"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(120) NOT NULL,
                    ""Description"" character varying(250),
                    ""Price"" numeric NOT NULL,
                    ""StockQuantity"" integer NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_Parts"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Parts""
                ADD COLUMN IF NOT EXISTS ""IsActive"" boolean NOT NULL DEFAULT true;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Parts""
                ADD COLUMN IF NOT EXISTS ""StockQuantity"" integer NOT NULL DEFAULT 0;
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Parts""
                ADD COLUMN IF NOT EXISTS ""Category"" character varying(100) NOT NULL DEFAULT 'General';
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Parts""
                ADD COLUMN IF NOT EXISTS ""VendorId"" integer NOT NULL DEFAULT 1;
            ");

            migrationBuilder.Sql(@"
                UPDATE ""Parts"" SET ""VendorId"" = 1 WHERE ""VendorId"" IS NULL;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_name = 'Parts'
                          AND column_name = 'StockQty'
                    ) THEN
                        EXECUTE 'UPDATE ""Parts"" SET ""StockQuantity"" = ""StockQty"" WHERE ""StockQuantity"" = 0';
                    END IF;
                END $$;
            ");

            migrationBuilder.CreateTable(
                name: "Vehicles",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    CustomerId = table.Column<int>(type: "integer", nullable: false),
                    Make = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    Model = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    Year = table.Column<int>(type: "integer", nullable: true),
                    LicensePlate = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    VehicleNumber = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Vehicles", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Vehicles_Customers_CustomerId",
                        column: x => x.CustomerId,
                        principalTable: "Customers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SalesInvoiceItems",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    InvoiceId = table.Column<int>(type: "integer", nullable: false),
                    PartId = table.Column<int>(type: "integer", nullable: false),
                    Quantity = table.Column<int>(type: "integer", nullable: false),
                    UnitPrice = table.Column<decimal>(type: "numeric", nullable: false),
                    PartName = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SalesInvoiceItems", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SalesInvoiceItems_Parts_PartId",
                        column: x => x.PartId,
                        principalTable: "Parts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_SalesInvoiceItems_SalesInvoices_InvoiceId",
                        column: x => x.InvoiceId,
                        principalTable: "SalesInvoices",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Customers",
                columns: new[] { "Id", "Address", "CreatedAt", "Email", "Name", "Phone" },
                values: new object[,]
                {
                    { 100, "Kathmandu", new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc), "anil.sharma@example.com", "Anil Sharma", "9801112233" },
                    { 101, "Lalitpur", new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc), "sita.karki@example.com", "Sita Karki", "9802223344" }
                });

            migrationBuilder.Sql(@"
                INSERT INTO ""Parts"" (""Id"", ""CreatedAt"", ""Description"", ""IsActive"", ""Name"", ""Price"", ""StockQuantity"", ""Category"", ""VendorId"")
                VALUES
                    (1, '2026-04-01T00:00:00Z', 'Front brake pad set', true, 'Brake Pad Set', 6800, 25, 'Brakes', 1),
                    (2, '2026-04-01T00:00:00Z', 'Premium oil filter', true, 'Oil Filter', 2200, 40, 'Fluids', 1),
                    (3, '2026-04-01T00:00:00Z', 'Engine air filter', true, 'Air Filter', 1800, 35, 'Engine', 1),
                    (4, '2026-04-01T00:00:00Z', 'Heavy-duty clutch plate', true, 'Clutch Plate', 9200, 18, 'Transmission', 1)
                ON CONFLICT (""Id"") DO NOTHING;
            ");

            migrationBuilder.InsertData(
                table: "SalesInvoices",
                columns: new[] { "Id", "CustomerId", "DiscountAmount", "DiscountApplied", "EmailSent", "GrandTotal", "InvoiceDate", "InvoiceNumber", "PaymentStatus", "StaffId", "TotalAmount" },
                values: new object[,]
                {
                    { 2000, 100, 1250m, true, false, 11250m, new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc), "INV-20260420-0001", "Paid", 1, 12500m },
                    { 2001, 101, 1650m, true, false, 14850m, new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc), "INV-20260421-0002", "Credit", 1, 16500m }
                });

            migrationBuilder.InsertData(
                table: "Vehicles",
                columns: new[] { "Id", "CreatedAt", "CustomerId", "LicensePlate", "Make", "Model", "VehicleNumber", "Year" },
                values: new object[,]
                {
                    { 1000, new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc), 100, "BA-2-PA-1234", "Honda", "City", "VIN-ANIL-001", 2022 },
                    { 1001, new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc), 101, "BA-3-PA-5678", "Toyota", "Corolla", "VIN-SITA-001", 2021 }
                });

            migrationBuilder.InsertData(
                table: "SalesInvoiceItems",
                columns: new[] { "Id", "InvoiceId", "PartId", "PartName", "Quantity", "UnitPrice" },
                values: new object[,]
                {
                    { 3000, 2000, 1, "Brake Pad Set", 1, 6800m },
                    { 3001, 2000, 4, "Clutch Plate", 1, 9200m },
                    { 3002, 2001, 2, "Oil Filter", 3, 2200m },
                    { 3003, 2001, 3, "Air Filter", 2, 1800m }
                });

            migrationBuilder.CreateIndex(
                name: "IX_SalesInvoices_CustomerId",
                table: "SalesInvoices",
                column: "CustomerId");

            migrationBuilder.CreateIndex(
                name: "IX_Customers_Email",
                table: "Customers",
                column: "Email",
                unique: true);


            migrationBuilder.CreateIndex(
                name: "IX_SalesInvoiceItems_InvoiceId",
                table: "SalesInvoiceItems",
                column: "InvoiceId");

            migrationBuilder.CreateIndex(
                name: "IX_SalesInvoiceItems_PartId",
                table: "SalesInvoiceItems",
                column: "PartId");

            migrationBuilder.CreateIndex(
                name: "IX_Vehicles_CustomerId",
                table: "Vehicles",
                column: "CustomerId");

            migrationBuilder.CreateIndex(
                name: "IX_Vehicles_LicensePlate",
                table: "Vehicles",
                column: "LicensePlate",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Vehicles_VehicleNumber",
                table: "Vehicles",
                column: "VehicleNumber",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_SalesInvoices_Customers_CustomerId",
                table: "SalesInvoices",
                column: "CustomerId",
                principalTable: "Customers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SalesInvoices_Customers_CustomerId",
                table: "SalesInvoices");

            migrationBuilder.DropTable(
                name: "SalesInvoiceItems");

            migrationBuilder.DropTable(
                name: "Vehicles");

            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Parts"" CASCADE;");

            migrationBuilder.DropTable(
                name: "Customers");

            migrationBuilder.DropIndex(
                name: "IX_SalesInvoices_CustomerId",
                table: "SalesInvoices");

            migrationBuilder.DeleteData(
                table: "SalesInvoices",
                keyColumn: "Id",
                keyValue: 2000);

            migrationBuilder.DeleteData(
                table: "SalesInvoices",
                keyColumn: "Id",
                keyValue: 2001);

            migrationBuilder.DropColumn(
                name: "StaffId",
                table: "SalesInvoices");

            migrationBuilder.RenameColumn(
                name: "TotalAmount",
                table: "SalesInvoices",
                newName: "Subtotal");

            migrationBuilder.RenameColumn(
                name: "InvoiceDate",
                table: "SalesInvoices",
                newName: "Date");

            migrationBuilder.RenameColumn(
                name: "DiscountAmount",
                table: "SalesInvoices",
                newName: "Discount");

            migrationBuilder.InsertData(
                table: "SalesInvoices",
                columns: new[] { "Id", "CustomerId", "Date", "Discount", "DiscountApplied", "EmailSent", "GrandTotal", "InvoiceNumber", "PaymentStatus", "Subtotal" },
                values: new object[,]
                {
                    { 1, 10, new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc), 1250m, true, false, 11250m, "INV-2026-1001", "Paid", 12500m },
                    { 2, 11, new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc), 1650m, true, false, 14850m, "INV-2026-1002", "Credit", 16500m }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "CreatedAt", "Email", "IsActive", "Name", "PasswordHash", "Phone", "Role", "UpdatedAt" },
                values: new object[,]
                {
                    { 10, new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc), "customer1@gearnxt.com", true, "Demo Customer 1", "DEMO_HASH", "9810000003", "Customer", null },
                    { 11, new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc), "customer2@gearnxt.com", true, "Demo Customer 2", "DEMO_HASH", "9810000004", "Customer", null }
                });
        }
    }
}
